### ISSUE TITLE
no yahoo weather - API change - 04.01.2018

### ISSUE THREAD

**Issue by Herbert-Testmann** [ioBroker/ioBroker.vis-timeandweather#5]
https://developer.yahoo.com/weather/

**Comment by Harald-B-Rupp** [comment]
Same Problem here, because of API Change no Data are anymore loaded. The new API's will require now Authentication and an API Key.

Important EOL Notice: As of Thursday, Jan. 3, 2019, the weather.yahooapis.com and query.yahooapis.com for Yahoo Weather API will be retired. 
To continue using our free Yahoo Weather APIs, use https://weather-ydn-yql.media.yahoo.com/forecastrss. Contact yahoo-weather-ydn-api@oath.com for credentials to onboard to this free Yahoo Weather API service.

**Comment by winterson0** [comment]
Same problem.

**Comment by m0rph2k** [comment]
Same problem.

**Comment by WaJoWi** [comment]
Please fix it!
Bitte beheben!

**Comment by TomT1965** [comment]
Same here...
Need to be fixed please

**Comment by GermanBluefox** [comment]
Es wird kein Fix dafür sein. Yahoo is dead.

**Comment by WaJoWi** [comment]
Würde ein anderer Wetterdienst funktionieren?
Would another weather service work?

**Comment by Herbert-Testmann** [comment]
The TimeAndWeather Widget for yahoo was only the "costom widget" with pre set data for yahoo, right?
Then we can use the costom widget in TimeAnsWeather with every other service, if we have a adapter in ioBroker for the service.
At this time it works with yr.no  and  OpenWeatherMap  adapter.

Litle Bugs in widget can you view at other issues.
